export const EMIT_SOCKET_INIT = 'EMIT_SOCKET_INIT';

export const EMIT_SOCKET_CONNECTION_UPDATE = 'EMIT_SOCKET_CONNECTION_UPDATE';

export const EMIT_SOCKET_ERROR = 'EMIT_SOCKET_ERROR';

export const EMIT_SOCKET_ERRORS_CLEAR = 'EMIT_SOCKET_ERRORS_CLEAR;';
